#!/usr/bin/perl

use FindBin;
use lib "$FindBin::Bin/mojo/lib";

use Mojolicious::Lite;
use Mojo::JSON;

@ARGV = qw/daemon/ unless @ARGV;

my $clients = {};

websocket '/' => sub {
    my $self = shift;
    my $tx = $self->tx;

    my $cid = "$tx";

    $clients->{$cid}->{tx} = $tx;
    $clients->{$cid}->{dots} = [];

    my $total_clients = keys %$clients;
    my $ip = $tx->remote_address;
    app->log->debug("Client '$ip' connected [$total_clients]");

    # Notify everybody that new client is connected
    _send_broadcast_status(clients => $total_clients);

    # Send all the current dots to the new client
    _send_dots($tx);

    # Send dots count to the new client
    _send_status($tx, dots => _count_dots());

    $self->receive_message(
        sub {
            my ($self, $message) = @_;

            my $json = Mojo::JSON->new;

            $message = $json->decode($message);
            return unless $message || $json->error;

            my $x   = $message->{x};
            my $y   = $message->{y};
            my $col = $message->{col};

            # Send a new dot to everybody
            _send_dot_broadcast($tx, $x, $y, $col);
        }
    );

    $self->finished(
        sub {
            delete $clients->{$cid};

            my $total_clients = keys %$clients;

            # Notify everybody that client has disconnected
            _send_broadcast_status(clients => $total_clients);

            app->log->debug('Client disconnected');
        }
    );
};

get '/' => 'index';

sub _send_dots {
    my $tx = shift;

    my @dots;
    foreach my $cid (keys %$clients) {
        push @dots, @{$clients->{$cid}->{dots}};
    }
    return unless @dots;

    $tx->send_json({type => 'dots', content => [@dots]});
}

sub _count_dots {
    return scalar map {@{$clients->{$_}->{dots}}} keys %$clients;
}

sub _send_dot_broadcast {
    my ($tx, $x, $y, $col) = @_;

    my $cid = "$tx";

    # Save dot
    my $dot = {x => $x, y => $y, col => $col};
    push @{$clients->{$cid}->{dots}}, $dot;

    # Send it to everyone
    _send_broadcast(type => 'dot', content => $dot);

    # Send dots count to everyone
    _send_broadcast_status(dots => _count_dots());
}

sub _send_broadcast_status {
    _send_broadcast(type => 'status', content => {@_});
}

sub _send_status {
    my $tx = shift;

    $tx->send_json({type => 'status', content => {@_}});
}

sub _send_broadcast {
    foreach my $cid (keys %$clients) {
        $clients->{$cid}->{tx}->send_json({@_});
    }
}

# see script/flash-policy-server
print "Remember, you need to also run script/flash-policy-server as root for this to work...\n";

app->start;

1;

__DATA__

@@ index.html.ep
% layout 'wrapper';
Please, enable JavaScript.<br /><br />

If your browser doesn't support Websockets,<br />
make sure you have Flash<br />
installed. It is used as workaround.

@@ layouts/wrapper.html.ep
% my $url = $self->req->url->to_abs->scheme($self->req->is_secure ? 'wss' : 'ws')->path('/');
<!doctype html><html>
    <head>
        <title>Presentation</title>
        <link rel="stylesheet" href="/main.css" type="text/css" />
        <script type="text/javascript" src="/jquery.min.js"></script>
        <script type="text/javascript" src="/jquery.json.min.js"></script>
        <script type="text/javascript">
            // Only load the flash fallback when needed
            if (!('WebSocket' in window)) {
                document.write([
                    '<scr'+'ipt type="text/javascript" src="web-socket-js/swfobject.js"></scr'+'ipt>',
                    '<scr'+'ipt type="text/javascript" src="web-socket-js/FABridge.js"></scr'+'ipt>',
                    '<scr'+'ipt type="text/javascript" src="web-socket-js/web_socket.js"></scr'+'ipt>'
                ].join(''));
            }
        </script>
        <script type="text/javascript">
            if (WebSocket.__initialize) {
                // Set URL of your WebSocketMain.swf here:
                WebSocket.__swfLocation = 'web-socket-js/WebSocketMain.swf';
            }

            var ws;
            var connected = false;

            function init() {
                connected = false;
                displayMessage('Connecting...');

                // Connect to WebSocket
                ws = new WebSocket('<%= $url %>');

                ws.onerror = function(e) {
                    displayMessage("Error: " + e);
                };

                // Set event handlers
                ws.onopen = function() {
                    connected = true;
                    displayMessage('Connected. Loading...');

                    initCanvas();
                };

                ws.onmessage = function(e) {
                    var data = $.evalJSON(e.data);

                    if (data == null) {
                    }
                    else if (data.type == 'message') {
                        displayMessage(data.content);
                    }
                    else if (data.type == 'slide') {
                        displayMessage(data.content.content);
                    }
                    else if (data.type == 'status') {
                        if (data.content.clients != null) {
                            $('#clients_status').html(data.content.clients);
                        }
                        if (data.content.dots != null) {
                            $('#dots_status').html(data.content.dots);
                        }
                    }
                    else if (data.type == 'dot') {
                        var content = data.content;

                        addPoint(content.x, content.y, content.col);
                    }
                    else if (data.type == 'dots') {
                        var content = data.content;

                        for (var i = 0; i < content.length; i++) {
                           addPoint(content[i].x, content[i].y, content[i].col);
                        }
                    }
                };

                ws.onclose = function() {
                    displayMessage('Disconnected. <a href="/">Reconnect</a>');
                }
            }

            function displayMessage(msg) {
                $('#canvas').html(msg);
            }

            function addPoint(x, y, col) {
                pointer = $('<span>').css({
                    'position':'absolute',
                    'background-color':col,
                    'width':'5px',
                    'height':'5px',
                    top: y,
                    left: x
                });

                $('#canvas').append(pointer);
            }

            function getRandomColor() {
                colors = new Array(14);
                colors[0]="0";
                colors[1]="1";
                colors[2]="2";
                colors[3]="3";
                colors[4]="4";
                colors[5]="5";
                colors[5]="6";
                colors[6]="7";
                colors[7]="8";
                colors[8]="9";
                colors[9]="a";
                colors[10]="b";
                colors[11]="c";
                colors[12]="d";
                colors[13]="e";
                colors[14]="f";

                var color = '';
                for (i = 0; i < 6; i++){
                    color += colors[Math.round(Math.random() * colors.length)]
                }

                return '#' + color;
            }

            function initCanvas() {
                var draw = false;
                var col = getRandomColor();

                $('#canvas').html('');

                //set it true on mousedown
                $('#canvas').mousedown(function(){draw=true;});

                //reset it on mouseup
                $('#canvas').mouseup(function(){draw=false;});

                $('#canvas').mousemove(function(e) {
                    //if mouse is down
                    if(draw == true) {
                        //addPoint(e.pageX, e.pageY, col);

                        ws.send($.toJSON({'x': e.pageX, 'y' : e.pageY, 'col' : col}));
                    }
                });
            }

            $(document).ready(function() {
                init();
            });
        </script>
    </head>
    <body>
        <div id="status">
            clients: <span id="clients_status">n/a</span><br />
            dots: <span id="dots_status">n/a</span><br />
        </div>
        <div class="container">
            <table border="0" height="100%" style="margin:auto">
            <tr><td style="vertical-align:middle">
                <div id="canvas">
                    <%== content %>
                </div>
            </td></tr>
            </table>
        </div>
    </body>
</html>
